#!/usr/bin/env node

const commander = require('commander');
const fs = require('fs');

const { fixDuplicates, listDuplicates } = require('./index');
const version = require('./package.json').version;

commander
    .version(version)
    .usage('[options] [yarn.lock path (default: yarn.lock)]')
    .option(
        '-s, --strategy <strategy>',
        'deduplication strategy. Valid values: fewer, highest. Default is "highest"',
        'highest'
    )
    .option('-l, --list', 'do not change yarn.lock, just output the diagnosis')
    .option('-f, --fail', 'if there are duplicates in yarn.lock, exit 1 for failure')
    .option(
        '--packages <packages>',
        'a comma separated list of packages to deduplicate. Defaults to all packages.',
        val => val.split(',').map(v => v.trim())
    )
    .option('--exclude <exclude>', 'a comma separated list of packages not to deduplicate.', val =>
        val.split(',').map(v => v.trim())
    )
    .option('--print', 'instead of saving the deduplicated yarn.lock, print the result in stdout');

commander.parse(process.argv);

if (commander.strategy !== 'highest' && commander.strategy !== 'fewer') {
    console.error(`Invalid strategy ${commander.strategy}`);
    commander.help();
}

const file = commander.args.length ? commander.args[0] : 'yarn.lock';

try {
    const yarnLock = fs.readFileSync(file, 'utf8');
    const useMostCommon = commander.strategy === 'fewer';

    if (commander.list) {
        const duplicates = listDuplicates(yarnLock, {
            useMostCommon,
            includePackages: commander.packages,
            excludePackages: commander.exclude,
        });
        duplicates.forEach(logLine => console.log(logLine));
        if (commander.fail && duplicates.length > 0) {
            process.exit(1);
        }
    } else {
        // https://github.com/yarnpkg/berry/blob/06443a7c050713f90f33d9a224cc37f7312cd28b/packages/yarnpkg-core/sources/Project.ts#L1510-L1515
        const header = `${[
            `# This file is generated by running "yarn install" inside your project.\n`,
            `# Manual changes might be lost - proceed with caution!\n`,
        ].join(``)}\n`;

        let dedupedYarnLock =
            header +
            fixDuplicates(yarnLock, {
                useMostCommon,
                includePackages: commander.packages,
                excludePackages: commander.exclude,
            });

        if (commander.print) {
            console.log(dedupedYarnLock);
        } else {
            const eolMatch = yarnLock.match(/(\r?\n)/);
            if (eolMatch && eolMatch[0] === '\r\n') {
                dedupedYarnLock = dedupedYarnLock.replace(/\n/g, '\r\n');
            }

            return fs.writeFileSync(file, dedupedYarnLock);
        }

        if (commander.fail && yarnLock !== dedupedYarnLock) {
            process.exit(1);
        }
    }

    process.exit(0);
} catch (e) {
    console.error(e);
    process.exit(1);
}
